/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.java.views;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import mvc.java.controllers.Controller;
import mvc.java.models.Model;
import mvc.java.libraries.UtilesApp;

/**
 *
 * @author JuanDavid
 */
public class View extends javax.swing.JFrame {

    //Referencias
    private Controller controller;
    private Properties prpview;
    
    public View() {
        //Inicializador antes de creacion de vista
        initBefore();

        //Creacion de la vista
        initComponents();

        //Inicializador antes de creacion de vista
        initAfter();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtRuta = new javax.swing.JTextField();
        btnAdjuntar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaTest");
        setMinimumSize(new java.awt.Dimension(582, 420));

        contentPane.setMinimumSize(new java.awt.Dimension(577, 415));
        contentPane.setLayout(null);

        jLabel1.setText("Adjuntar archivo :");
        contentPane.add(jLabel1);
        jLabel1.setBounds(21, 11, 87, 14);
        contentPane.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 540, 10);

        txtRuta.setEditable(false);
        contentPane.add(txtRuta);
        txtRuta.setBounds(30, 40, 300, 30);

        btnAdjuntar.setText("Adjuntar");
        btnAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarActionPerformed(evt);
            }
        });
        contentPane.add(btnAdjuntar);
        btnAdjuntar.setBounds(340, 50, 75, 23);
        btnAdjuntar.getAccessibleContext().setAccessibleName("btnAdjuntar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        contentPane.add(btnLimpiar);
        btnLimpiar.setBounds(430, 50, 65, 23);
        btnLimpiar.getAccessibleContext().setAccessibleName("btnLimpiar");

        contentPane.add(jSeparator2);
        jSeparator2.setBounds(20, 30, 540, 10);

        txtSalida.setEditable(false);
        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        contentPane.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 520, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarActionPerformed
        //Creamos el objeto JFileChooser
        JFileChooser fc = new JFileChooser();

        //Indicamos lo que podemos seleccionar
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");

        //Le indicamos el filtro
        fc.setFileFilter(filtro);

        //Abrimos la ventana, guardamos la opcion seleccionada por el usuario
        int seleccion = fc.showOpenDialog(contentPane);

        //Si el usuario, pincha en aceptar
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            //Seleccionamos el fichero
            File fichero = fc.getSelectedFile();

            //Ecribe la ruta del fichero seleccionado en el campo de texto
            txtRuta.setText(fichero.getAbsolutePath());
            
            txtSalida.setText(controller.obtenerArchivotxt(fichero));
            
        }
    }//GEN-LAST:event_btnAdjuntarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtRuta.setText("");
        txtSalida.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    private void initBefore() {
        //Controller
        controller = new Controller();

        //Cargar propiedades
        prpview = UtilesApp.cargarPropiedades("view.properties");
    }
    
    private void initAfter() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntar;
    private javax.swing.JButton btnLimpiar;
    private java.awt.Panel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
